[package]
name = "nonogram_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-set = "0.8.0"
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.28.1"
rand = "0.8.5"
regex = "1.11.1"
